# -*- ruby -*-

require "rubygems"
require "hoe"

Hoe.plugin :isolate
Hoe.plugin :seattlerb

Hoe.spec "otask" do
  developer "Ryan Davis", "ryand-ruby@zenspider.com"

  self.rubyforge_name = "seattlerb"
  self.readme_file = "README.txt"

  dependency "rb-appscript", "~> 0.6.1"
  dependency "amatch",       "~> 0.2"
  dependency "chronic",      "~> 0.6"
end

# vim: syntax=ruby
